export const categoryOptions = [
    { label: "Electronics", value: "electronics" },
    { label: "Smartphones", value: "smartphones" },
    { label: "Laptops", value: "laptops" },
    { label: "Audio Devices", value: "audio" },
    { label: "Wearables", value: "wearables" },

    { label: "Clothing", value: "clothing" },
    { label: "Shoes", value: "shoes" },
    { label: "Accessories", value: "accessories" },

    { label: "Gaming", value: "gaming" },
    { label: "Home Appliances", value: "home_appliances" },

    { label: "Cameras", value: "cameras" },
    { label: "Furniture", value: "furniture" },
    { label: "Beauty & Health", value: "beauty_health" },
  ]

  export const statusStyles = {
    active: "bg-green-500/10 text-green-400 border border-green-500/20",
    draft: "bg-amber-500/10 text-amber-400 border border-amber-500/20",
    archived: "bg-red-500/10 text-red-400 border border-red-500/20",
    inactive: "bg-gray-500/10 text-gray-400 border border-gray-500/20",
  } as const
  
  export type ProductStatus = keyof typeof statusStyles
  
  export interface ProductItem {
    id: string
    image: string
    product: string
    sku: string
    category: string
    price: number
    status: ProductStatus
    rating: number
    sales: number
    createdAt: string
    description?: string
    stock?: number
  }

  export const products: ProductItem[] = [
    {
      id: "P1001",
      image: "/images/product-1.jpg",
      product: "iPhone 15 Pro",
      sku: "APL-IP15P-256",
      category: "smartphones",
      price: 1199,
      status: "active",
      rating: 4.8,
      sales: 1520,
      createdAt: "2025-01-12",
      description: "Experience the ultimate iPhone with the A17 Pro chip, a titanium design, and a powerful new camera system.",
      stock: 45,
    },
    {
      id: "P1002",
      image: "/images/product-2.jpg",
      product: "Samsung Galaxy S24",
      sku: "SMS-S24-256",
      category: "smartphones",
      price: 1099,
      status: "active",
      rating: 4.7,
      sales: 1340,
      createdAt: "2025-02-05",
      description: "The Galaxy S24 features Galaxy AI, a stunning LTPO display, and an improved camera for capturing every moment.",
      stock: 32,
    },
    {
      id: "P1003",
      image: "/images/product-3.jpg",
      product: "MacBook Air M3",
      sku: "APL-MBA-M3",
      category: "laptops",
      price: 1499,
      status: "draft",
      rating: 4.9,
      sales: 980,
      createdAt: "2025-01-20",
      description: "The incredibly thin and fast MacBook Air with the M3 chip, designed for portability and performance.",
      stock: 15,
    },
    {
      id: "P1004",
      image: "/images/product-4.jpg",
      product: "Dell XPS 13",
      sku: "DLL-XPS13-2025",
      category: "laptops",
      price: 1299,
      status: "active",
      rating: 4.6,
      sales: 860,
      createdAt: "2024-12-15",
      description: "The Dell XPS 13 combines a stunning InfinityEdge display with the latest Intel Core processors for premium productivity.",
      stock: 20,
    },
    {
      id: "P1005",
      image: "/images/product-5.jpg",
      product: "Sony WH-1000XM5",
      sku: "SNY-WH1000XM5",
      category: "audio",
      price: 399,
      status: "active",
      rating: 4.8,
      sales: 2200,
      createdAt: "2025-03-10",
      description: "Industry-leading noise canceling and exceptional sound quality in a comfortable, modern design.",
      stock: 58,
    },
    {
      id: "P1006",
      image: "/images/product-6.jpg",
      product: "Apple AirPods Pro 2",
      sku: "APL-APP2",
      category: "audio",
      price: 249,
      status: "active",
      rating: 4.7,
      sales: 3100,
      createdAt: "2025-02-28",
      description: "AirPods Pro features up to 2x more Active Noise Cancellation, plus Adaptive Transparency, and Personalized Spatial Audio.",
      stock: 120,
    },
    {
      id: "P1007",
      image: "/images/product-7.jpg",
      product: "Nike Air Max 270",
      sku: "NKE-AM270",
      category: "shoes",
      price: 149,
      status: "active",
      rating: 4.5,
      sales: 1800,
      createdAt: "2024-11-11",
      description: "Nike's first lifestyle Air Max brings you style, comfort and big attitude.",
      stock: 85,
    },
    {
      id: "P1008",
      image: "/images/product-8.jpg",
      product: "Adidas Ultraboost 22",
      sku: "ADS-UB22",
      category: "shoes",
      price: 179,
      status: "draft",
      rating: 4.6,
      sales: 1400,
      createdAt: "2025-01-05",
      description: "A little extra push. The Ultraboost running shoes serve up comfort and responsiveness.",
      stock: 42,
    },
    {
      id: "P1009",
      image: "/images/product-9.jpg",
      product: "Leather Wallet",
      sku: "ACC-WLT-001",
      category: "accessories",
      price: 49,
      status: "active",
      rating: 4.3,
      sales: 500,
      createdAt: "2024-10-10",
      description: "Handcrafted genuine leather wallet with RFID protection and multiple card slots.",
      stock: 150,
    },
    {
      id: "P1010",
      image: "/images/product-10.jpg",
      product: "Smart Watch Series 9",
      sku: "APL-SW9",
      category: "wearables",
      price: 499,
      status: "active",
      rating: 4.7,
      sales: 2100,
      createdAt: "2025-03-01",
      description: "Smarter. Brighter. Mightier. Apple Watch Series 9 is more capable than ever.",
      stock: 64,
    },
    {
      id: "P1011",
      image: "/images/product-11.jpg",
      product: "Gaming Keyboard RGB",
      sku: "GMG-KB-RGB",
      category: "gaming",
      price: 89,
      status: "active",
      rating: 4.4,
      sales: 950,
      createdAt: "2025-01-18",
      description: "Mechanical gaming keyboard with customizable RGB backlighting and tactile switches.",
      stock: 38,
    },
    {
      id: "P1012",
      image: "/images/product-12.jpg",
      product: "Gaming Mouse Pro",
      sku: "GMG-MS-PRO",
      category: "gaming",
      price: 59,
      status: "active",
      rating: 4.6,
      sales: 1200,
      createdAt: "2025-02-02",
      description: "High-precision gaming mouse with adjustable DPI and ergonomic design.",
      stock: 72,
    },
    {
      id: "P1013",
      image: "/images/product-13.jpg",
      product: "Canon EOS R10",
      sku: "CNR-R10",
      category: "cameras",
      price: 999,
      status: "draft",
      rating: 4.8,
      sales: 670,
      createdAt: "2024-12-22",
      description: "A versatile mirrorless camera that's perfect for content creators and enthusiasts.",
      stock: 12,
    },
    {
      id: "P1014",
      image: "/images/product-14.jpg",
      product: "Sony Alpha A7 III",
      sku: "SNY-A7III",
      category: "cameras",
      price: 1999,
      status: "active",
      rating: 4.9,
      sales: 540,
      createdAt: "2025-01-08",
      description: "Full-frame mirrorless camera with outstanding imaging capability and high-speed performance.",
      stock: 8,
    },
    {
      id: "P1015",
      image: "/images/product-15.jpg",
      product: "Office Chair Ergonomic",
      sku: "FUR-CHAIR-ERG",
      category: "furniture",
      price: 199,
      status: "active",
      rating: 4.5,
      sales: 760,
      createdAt: "2024-09-30",
      description: "Maintain proper posture and stay comfortable during long work hours with this ergonomic office chair.",
      stock: 25,
    },
    {
      id: "P1016",
      image: "/images/product-16.jpg",
      product: "Wooden Study Desk",
      sku: "FUR-DESK-WOOD",
      category: "furniture",
      price: 249,
      status: "draft",
      rating: 4.4,
      sales: 620,
      createdAt: "2024-11-25",
      description: "Spacious and durable wooden study desk, perfect for home offices and students.",
      stock: 14,
    },
    {
      id: "P1017",
      image: "/images/product-17.jpg",
      product: "Face Serum Glow",
      sku: "BEA-SRM-GLW",
      category: "beauty_health",
      price: 29,
      status: "active",
      rating: 4.2,
      sales: 2400,
      createdAt: "2025-03-15",
      description: "A lightweight serum that brightens and hydrates for a glowing complexion.",
      stock: 200,
    },
    {
      id: "P1018",
      image: "/images/product-18.jpg",
      product: "Vitamin C Tablets",
      sku: "BEA-VITC-60",
      category: "beauty_health",
      price: 19,
      status: "active",
      rating: 4.3,
      sales: 3200,
      createdAt: "2025-02-10",
      description: "Daily Vitamin C supplement to support your immune system and overall health.",
      stock: 500,
    },
    {
      id: "P1019",
      image: "/images/product-19.jpg",
      product: "LED Desk Lamp",
      sku: "HAP-LAMP-LED",
      category: "home_appliances",
      price: 39,
      status: "active",
      rating: 4.5,
      sales: 1100,
      createdAt: "2024-10-28",
      description: "Dimmable LED desk lamp with multiple color modes and a built-in USB charging port.",
      stock: 48,
    },
    {
      id: "P1020",
      image: "/images/product-20.jpg",
      product: "Air Fryer 5L",
      sku: "HAP-AFRY-5L",
      category: "home_appliances",
      price: 129,
      status: "active",
      rating: 4.7,
      sales: 1950,
      createdAt: "2025-01-30",
      description: "Cook your favorite fried foods with little to no oil for a healthier alternative.",
      stock: 35,
    },
  ]
